name: CreativeSuite
description: Extended tools and commands for working in creative worlds in Minecraft.
version: 2.0.0
author: danae
website: https://github.com/danae/creativesuite
main: dev.danae.creativesuite.plugin.CreativeSuitePlugin
api-version: 1.20


commands:
  creativesuite:
    description: Executes various administration commands.
    usage: "Usage: /<command> reload | version"

  alias:
    description: Defines shared aliases for long commands.
    usage: "Usage: /<command> list | overwrite <name> <cmd> | remove <name> | run <name> | save <name> <cmd>"
    aliases: [al]

  run:
    description: Runs shared aliases for long commands.
    usage: "Usage: /<command> <name>"
    aliases: [r]

  hotbar:
    description: Defines shared hotbars.
    usage: "Usage: /<command> list | load <name> | overwrite <name> | remove <name> | save <name>"
    aliases: [hb]

  charmap:
    description: Defines shared Unicode characters for easy copying and pasting.
    usage: "Usage: /<command> [add <characters> | remove <characters>]"
    aliases: [cm]
    
    
permissions:
  creativesuite.admin:
    description: Allows the player to use the /creativesuite command.
    default: op

  creativesuite.hotbar:
    description: Allows the player to use the /hotbar command.
    default: true
    children:
      gregocommands.hotbar.list: true
      gregocommands.hotbar.load: true
      gregocommands.hotbar.remove: true
      gregocommands.hotbar.save: true

  creativesuite.hotbar.list:
    description: Allows the player to use the /hotbar list command.
    default: true

  creativesuite.hotbar.load:
    description: Allows the player to use the /hotbar load command.
    default: true

  creativesuite.hotbar.remove:
    description: Allows the player to use the /hotbar remove command.
    default: true

  creativesuite.hotbar.save:
    description: Allows the player to use the /hotbar save command.
    default: true

  creativesuite.charmap:
    description: Allows the player to use the /charmap command.
    default: true
    children:
      gregocommands.charmap.list: true
      gregocommands.charmap.add: true
      gregocommands.charmap.remove: true

  creativesuite.charmap.list:
    description: Allows the player to use the /charmap command.
    default: true

  creativesuite.charmap.add:
    description: Allows the player to use the /charmap add command.
    default: true

  creativesuite.charmap.remove:
    description: Allows the player to use the /charmap remove command.
    default: true

  creativesuite.alias:
    description: Allows the player to use the /alias command.
    default: true
    children:
      gregocommands.hotbar.list: true
      gregocommands.hotbar.remove: true
      gregocommands.hotbar.run: true
      gregocommands.hotbar.save: true

  creativesuite.alias.list:
    description: Allows the player to use the /alias list command.
    default: true

  creativesuite.alias.remove:
    description: Allows the player to use the /alias remove command.
    default: true

  creativesuite.alias.run:
    description: Allows the player to use the /alias run and /run commands.
    default: true

  creativesuite.alias.save:
    description: Allows the player to use the /alias save command.
    default: true