name: CreativeSuite
description: Extended tools and commands for working in creative worlds in Minecraft.
version: 2.1.0
author: danae
website: https://github.com/arloheim/creativesuite
main: dev.danae.creativesuite.plugin.CreativeSuitePlugin
api-version: 1.20


commands:
  creativesuite:
    description: Executes various administration commands.
    usage: "Usage: /<command> reload | version"

  alias:
    description: Defines shared aliases.
    usage: "Usage: /<command> inspect <name> | list | overwrite <name> <cmd> | remove <name> | rename <name> <destination> | run <name> | save <name> <cmd>"
    aliases: [al]

  run:
    description: Executes shared aliases.
    usage: "Usage: /<command> <name>"
    aliases: [r]

  hotbar:
    description: Defines shared hotbars.
    usage: "Usage: /<command> list | load <name> | overwrite <name> | remove <name> | rename <name> <destination> | save <name>"
    aliases: [hb]

  charmap:
    description: Defines shared Unicode characters for easy copying and pasting.
    usage: "Usage: /<command> [add <characters> | remove <characters>]"
    aliases: [cm]

  clearfill:
    description: Clears a player's inventory and fill it with a hotbar.
    usage: "Usage: /<command> [player]"
    aliases: [cf]

  nightvision:
    description: Sets or resets a player's night vision effect.
    usage: "Usage: /<command> [off | on | toggle] [player]"
    alisases: [nv]

  drop:
    description: Drops a gravity-affected block at a location.
    usage: "Usage: /<command> <block_material> [player | location]"

  anvil:
    description: Drops an anvil at a location.
    usage: "Usage: /<command> [player | location]"

  smite:
    description: Executes a lightning effect at a location.
    usage: "Usage: /<command> [player | location]"
    
    
permissions:
  creativesuite.admin:
    description: Allows the player to use the /creativesuite command.
    default: op

  creativesuite.alias:
    description: Allows the player to use the /alias command.
    default: op
    children:
      creativesuite.alias.inspect: true
      creativesuite.alias.list: true
      creativesuite.alias.remove: true
      creativesuite.alias.rename: true
      creativesuite.alias.run: true
      creativesuite.alias.save: true

  creativesuite.alias.inspect:
    description: Allows the player to use the /alias inspect command.
    default: true

  creativesuite.alias.list:
    description: Allows the player to use the /alias list command.
    default: true

  creativesuite.alias.remove:
    description: Allows the player to use the /alias remove command.
    default: op

  creativesuite.alias.rename:
    description: Allows the player to use the /alias rename command.
    default: op

  creativesuite.alias.run:
    description: Allows the player to use the /alias run and /run commands.
    default: true

  creativesuite.alias.save:
    description: Allows the player to use the /alias save command.
    default: op

  creativesuite.hotbar:
    description: Allows the player to use the /hotbar command.
    default: op
    children:
      creativesuite.hotbar.list: true
      creativesuite.hotbar.load: true
      creativesuite.hotbar.remove: true
      creativesuite.hotbar.rename: true
      creativesuite.hotbar.save: true

  creativesuite.hotbar.list:
    description: Allows the player to use the /hotbar list command.
    default: true

  creativesuite.hotbar.load:
    description: Allows the player to use the /hotbar load command.
    default: true

  creativesuite.hotbar.rename:
    description: Allows the player to use the /hotbar rename command.
    default: op

  creativesuite.hotbar.remove:
    description: Allows the player to use the /hotbar remove command.
    default: op

  creativesuite.hotbar.save:
    description: Allows the player to use the /hotbar save command.
    default: op

  creativesuite.charmap:
    description: Allows the player to use the /charmap command.
    default: op
    children:
      creativesuite.charmap.list: true
      creativesuite.charmap.add: true
      creativesuite.charmap.remove: true

  creativesuite.charmap.list:
    description: Allows the player to use the /charmap command.
    default: true

  creativesuite.charmap.add:
    description: Allows the player to use the /charmap add command.
    default: op

  creativesuite.charmap.remove:
    description: Allows the player to use the /charmap remove command.
    default: op

  creativesuite.tools:
    description: Allows the player to use the tools commands.
    default: true
    children:
      creativesuite.tools.clearfill: true
      creativesuite.tools.nightvision: true
      creativesuite.tools.drop: true
      creativesuite.tools.smite: true

  creativesuite.tools.others:
    description: Allows the player to use the tools commands on other players.
    default: op
    children:
      creativesuite.tools.clearfill.others: true
      creativesuite.tools.nightvision.others: true

  creativesuite.tools.clearfill:
    description: Allows the player to use the /clearfill command.
    default: true

  creativesuite.tools.clearfill.others:
    description: Allows the player to use the /clearfill command on other players.
    default: true

  creativesuite.tools.nightvision:
    description: Allows the player to use the /nnightvision command.
    default: true

  creativesuite.tools.nightvision.others:
    description: Allows the player to use the /nnightvision command on other players.
    default: true

  creativesuite.tools.drop:
    description: Allows the player to use the /drop and /anvil commands.
    default: true

  creativesuite.tools.smite:
    description: Allows the player to use the /smite command.
    default: true